
@url=https://localhost:7001/api
##@url = https://kontrasepsikb.ocphapp.tech/api

@auth=bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoib2NwaDIzQGhvdG1haWwuY29tIiwianRpIjoiMmFiYzFiYWItZDg1NS00MzNlLWEyMjktMjFjZjIxNjg1NzI0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiUGFzaWVuIiwiZXhwIjoxNjYzNjY2MjA3LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MDg2LyIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcwODYvIn0.czvQLScPEZv3eFz8hvM9iH9n1uCtVvo8lmU09e1J8Io

POST {{url}}/ACCOUNT/login HTTP/1.1
Content-Type: application/json

{"userName":"ocph23@hotmail.com", "password":"Sony@77"}


####

GET  {{url}}/pengajuan/1 HTTP/1.1
Content-Type: application/json
Authorization: {{auth}}


#######

POST  {{url}}/pengajuan HTTP/1.1
Content-Type: application/json
Authorization: {{auth}}

{"Id":0,"AnakHidupLaki":0,"AnakHidupPerempuan":0,"UmurAnakTerkecilTahun":0,"UmurAnakTerkecilBulan":0,"StatusKB":true,"CaraKBTerakhir":{"IdView":"00004","Id":4,"Nama":"Kondom","Keterangan":"kondom"},"TerakhirHaid":"2022-09-19T18:20:53.5519074+09:00","Hamil":false,"Menyusui":false,"JumlahKehamilan":0,"JumlahPersalinan":0,"JumlahKeguguran":0,"SakitKuning":false,"PendarahanPervaginam":false,"KeputihanYangLama":false,"Tumor":false,"Keadaan":0,"BeratBadan":0,"TekananDarah":"","PosisiRahim":0,"AlatKontrasepsiPilihan":{"IdView":"00006","Id":6,"Nama":"Suntikan","Keterangan":"suntik"},"TanggalDilayani":null,"TanggalDicabut":null,"TanggalKembali":null,"PenanggungJawab":"","Kunjungan":null,"Petugas":null,"Radang":false,"KeganasanGinekologi":false,"Diabetes":false,"PemekuanDarah":false,"RadangOrchitis":false,"KeganasanGinekologi2":false,"Tanggal":"2022-09-19T18:20:53.5519403+09:00","PesertaId":0,"NamaPeserta":"","AlamatPeserta":""}

#####

PUT {{url}}/pengajuan?id=1 HTTP/1.1
Content-Type: application/json
Authorization: {{auth}}

{
  "id": 1,
  "terakhirHaid": "2022-08-24T00:00:00",
  "hamil": false,
  "menyusui": false,
  "jumlahKehamilan": 0,
  "jumlahPersalinan": 0,
  "jumlahKeguguran": 0,
  "sakitKuning": false,
  "pendarahanPervaginam": false,
  "keputihanYangLama": false,
  "tumor": false,
  "keadaan": 0,
  "beratBadan": 0,
  "tekananDarah": "180/50",
  "posisiRahim": 0,
  "alatKontrasepsiPilihan": {
    "id": 2,
    "nama": "Pil KB",
    "keterangan": "Minum OBAT",
    "idView": "00003"
  },
  "tanggalDilayani": null,
  "tanggalDicabut": null,
  "penanggungJawab": "",
  "kunjungan": null,
  "petugas": null,
  "radang": false,
  "keganasanGinekologi": false,
  "diabetes": false,
  "pemekuanDarah": false,
  "radangOrchitis": false,
  "keganasanGinekologi2": false,
  "tanggal": "0001-01-01T00:00:00"
}

####

GET {{url}}/bypetugas/1 HTTP/1.1
Content-Type: application/json




#########


POST https://fcm.googleapis.com/fcm/send HTTP/1.1
Content-Type: application/json
Authorization: key=AAAAj9FjpgY:APA91bGd-U2WFbvjrtF335cyaqmBob1djVqJ3R8z_jFqx1uzVKRfCFerXa55RhJftnYtE8GMbMIWU2kH5dCcRszXxkafnP8kGGjerDEC_L60XNkvCIduXglaIqT6187bSaxgLAZarq8a
Sender:id=617693292038

{
  
  "to": "ctVsw91uQ3qU3PqSrfetfb:APA91bF7LBsOkJOpx7VQMpmzMcesZLZmJ32Hcapbvd40EljorDNRDu0qfao_4W-b5y78tnxp26gLlIggCmlJBg-n4E-uvrpg65xRHIyMxj4ipQO6umdUJUlNPzta49NqsNpj3KTgzY1o",
  "priority":"high","notification":{"title":"BKKBN","body":"Dengan Schedule Kunjungan Berikut Tanggal 10/09/2022","image":"https://jateng.bkkbn.go.id/wp-content/uploads/2020/09/cropped-LOGO-BKKBN-2020-KUPU2.png","isScheduled":true,"scheduledTime":"2022-09-10 13:09:33"}
  }

####