name: Android

on:
  push:
    branches: [ "android" ]
  pull_request:
    branches: [ "android" ]

jobs:
  build-android:
    runs-on: windows-2022
    name: Android Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup keystore file
        run: |
          echo "${{ secrets.KEYSTORE }}" > ocph23.keystore.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_GPG_PASSWORD }}" --batch ocph23.keystore.asc > ocph23.keystore
      
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true
          
#       - uses: actions/setup-java@v2
#         with:
#           distribution: 'microsoft'
#           java-version: '11'
     
      - name: Install MAUI Workloads
        run: |
          dotnet workload install android --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore MainApp/MainApp.csproj

      - name: Build MAUI Android
        run: dotnet build MainApp/MainApp.csproj -c Release -f net6.0-android /p:AndroidSigningKeyStore=ocph23.keystore /p:AndroidSigningKeyAlias=Ocph23 /p:AndroidSigningKeyPass="${{ secrets.KEYSTORE_PASSWORD }}" /p:AndroidSigningStorePass="${{ secrets.KEYSTORE_ALIAS_PASSWORD }}" --no-restore

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: android-ci-build
          path: | 
            ./**/*.aab
            ./**/*.apk
